import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { remark } from "remark";
import remarkGfm from "remark-gfm";

const root = process.cwd();
const postsDirectory = path.join(root, "posts");
const outputFile = path.join(root, "src", "generated", "posts.ts");

function formatTitle(slug) {
  return slug.split("-").filter(Boolean).map((word) => word.charAt(0).toUpperCase() + word.slice(1)).join(" ");
}

function stripPositions(node) {
  delete node.position;
  if (Array.isArray(node.children)) node.children.forEach(stripPositions);
}

function getExcerpt(content) {
  return content.replace(/^---[\s\S]*?---/, "")
    .replace(/[#>*_\-[\]]/g, "")
    .split("\n").map((line) => line.trim()).find(Boolean);
}

function getHeadingTitle(content) {
  return content.split("\n").map((line) => line.trim())
    .find((line) => line.startsWith("# "))?.replace(/^#\s+/, "").trim();
}

function normalizeDate(value) {
  if (value instanceof Date && !Number.isNaN(value.getTime())) return value.toISOString().slice(0, 10);
  if (typeof value === "number") return new Date(value).toISOString().slice(0, 10);
  if (typeof value !== "string") return undefined;
  const match = value.match(/\d{4}[-/.]\d{1,2}[-/.]\d{1,2}/);
  return match ? match[0].replace(/[/.]/g, "-").split("-").map((part, i) => i === 0 ? part.padStart(4, "0") : part.padStart(2, "0")).join("-") : undefined;
}

if (!fs.existsSync(postsDirectory)) fs.mkdirSync(postsDirectory, { recursive: true });
if (!fs.existsSync(path.dirname(outputFile))) fs.mkdirSync(path.dirname(outputFile), { recursive: true });

const posts = await Promise.all(
  fs.readdirSync(postsDirectory).filter((fileName) => fileName.endsWith(".md")).map(async (fileName) => {
    const slug = fileName.replace(/\.md$/, "");
    const source = fs.readFileSync(path.join(postsDirectory, fileName), "utf8");
    const { data, content } = matter(source);
    const parsed = remark().use(remarkGfm).parse(content);
    stripPositions(parsed);
    return {
      slug,
      title: typeof data.title === "string" ? data.title : getHeadingTitle(content) ?? formatTitle(slug),
      description: typeof data.description === "string" ? data.description : getExcerpt(content) ?? "Read this SparkRelay post.",
      date: normalizeDate(data.date) ?? normalizeDate(fileName),
      pinned: data.pinned === true,
      content: parsed,
    };
  })
);

posts.sort((a, b) => {
  if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
  return (b.date ?? "").localeCompare(a.date ?? "");
});

const generated = `// Generated by scripts/generate-posts.mjs. Do not edit manually.
import type { Root } from "mdast";

export type GeneratedPost = {
  slug: string;
  title: string;
  description: string;
  date?: string;
  pinned: boolean;
  content: Root;
};

export const generatedPosts = ${JSON.stringify(posts, null, 2)} satisfies GeneratedPost[];
`;

fs.writeFileSync(outputFile, generated);
console.log(`Generated ${posts.length} post(s).`);
